# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the biconnected components of a phylogeny
#'
#' @title Biconnected Components
#' @description Find the biconnected components of a phylogeny
#' @param x A single integer.
#' @details biconnected components
#' @export
NULL

biconnectedComponents <- function(edges, rt, nNode) {
    .Call(`_SiPhyNetwork_biconnectedComponents`, edges, rt, nNode)
}

