# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the biconnected components of a phylogeny
#'
#' @title Biconnected Components
#' @description Find the biconnected components of a phylogeny
#' @param edges The `edge` matrix of a `phylo` object.
#' @param rt The root node of the phylogeney
#' @param nNode The number of nodes in the tree
#' @details biconnected components
#' @export
biconnectedComponents <- function(edges, rt, nNode) {
    .Call(`_SiPhyNetwork_biconnectedComponents`, edges, rt, nNode)
}

