# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
NULL

biconnectedComponents <- function(edges, rt, nNode) {
    .Call('_NetSim_biconnectedComponents', PACKAGE = 'NetSim', edges, rt, nNode)
}

